### ISSUE TITLE
Remove explicit sh from command spawning

### ISSUE THREAD

**Issue by max-mapper** [limey-bean/Anacapa#29]
During my containerization process I've been getting `source: command not found` errors. I tracked it down to usage of `sh` explicitly in the various Anacapa shell scripts. 

So I would recommend changing lines like this:

```
sh ~/Anacapa_db/scripts/anacapa_release_V1.sh
```

To simply this:

```
~/Anacapa_db/scripts/anacapa_release_V1.sh
```

Since all of the `.sh` files have `#!/bin/bash` at the top putting `sh` before them in the commands is unnecessary, and in fact is overriding `bash` and forcing it to use `sh`, which is causing my issue here.

The reason is:

https://stackoverflow.com/questions/13702425/source-command-not-found-in-sh-shell

```
/bin/sh is usually some other shell trying to mimic The Shell. Many distributions use /bin/bash for sh, it supports source. On Ubuntu, though, /bin/dash is used which does not support source. If you cannot edit the script, try to change the shell which runs it.
```

I think the version of `sh` on Hoffman is bash, but on other systems (such as in my Ubuntu container) the `sh` doesn't support `source`.

**Comment by jessegomer** [comment]
Hey, what do you think of changing it to call bash explicitly?  I am concerned some users will not know how to make the intermediate scripts that are generated executable.

**Comment by max-mapper** [comment]
@jessegomer oops sorry never responded, yea that would work too!

**Comment by max-mapper** [comment]
this is almost done except the lines https://github.com/limey-bean/Anacapa/blob/8b87d6745442c4cb68fe6b97481418492336aa2a/Anacapa_db/anacapa_QC_dada2.sh#L215-L217 embed `sh` in the generated files rather than `bash`

**edit** also `sh` is embedded in the generated blca scripts too
