### ISSUE TITLE
muscle in db folder?

### ISSUE THREAD

**Issue by limey-bean** [limey-bean/Anacapa#31]
We should have the user add muscle to the anacapa folder? i suppose we can just use the config...

**Comment by max-mapper** [comment]
From my standpoint it would be great if the path to muscle was declared in the config. The config is kind of nice because its sort of the only place (excluding all the R dependencies) where all the dependencies are more or less listed.

**Comment by limey-bean** [comment]
I agree and added the muscle path to the config folder!  It appears to work
