### ISSUE TITLE
merge_asv.py bug

### ISSUE THREAD

**Issue by limey-bean** [limey-bean/Anacapa#32]
If dada2 does not generate a nochim_unmerged<metabarcode>.txt, then the merge_asv.py file will throw an error and not build the summary table required to append the blca results.

**Comment by limey-bean** [comment]
no a bug in merged_asv, but bug in shell script that calls it (run_bowtie2_blca.sh).

Made partial fix with if else statement, but should also fix for cases where an unpaired F or R file is missing.

**Comment by jessegomer** [comment]
Hi, I will fix this in the script by checking if the file exists and has content before trying to load. I think this will be the cleanest solution

**Comment by jessegomer** [comment]
I pushed this fix, closing the issue now

**Comment by limey-bean** [comment]
Thanks you so much, Jesse!  I hope you are having a great holiday!
