### ISSUE TITLE
clarifications in README

### ISSUE THREAD

**Issue by gauravsk** [limey-bean/Anacapa#50]
- [x] Line 62 of README: 
> All reads are first globally aligned against the **CRUX** database using **Bowtie 2**.

Should this read "All ASVs are first globally...". Similarly in the following sentence.

- [x] Line 29 of README indicates that there are CRUX DBs available in DRYAD, but later on (Line 208) the link is to a google drive- which will you want to use in the long term?

**Comment by limey-bean** [comment]
yes should read "All ASVs are first globally..."

Dryad

**Comment by gauravsk** [comment]
Are the DBs up on dryad already? do we have a link?
