### ISSUE TITLE
Write check_paired.pl in python?

### ISSUE THREAD

**Issue by gauravsk** [limey-bean/Anacapa#6]
It looks a little sloppy to have a single random perl script thrown in with everything else here- can we rewrite in Python? Probably good for long-term maintenance etc. I'm probably not the best person to do it but can do it if needed.

**Comment by jessegomer** [comment]
@gauravsk This sounds like a good suggestion

**Comment by limey-bean** [comment]
I would love it if someone wrote a new one.  Please fix at will!

**Comment by gauravsk** [comment]
not done yet; see data cleaning to-do list
