### ISSUE TITLE
Can't get to run ANACAPA

### ISSUE THREAD

**Issue by juanboja** [limey-bean/Anacapa#61]
I am trying to use the ANACAPA pipeline instead of the whole dada2 on R script. 

I have installed all the programs needed and input them in anacapa_config.sh as shown below. 

```
MODULE_SOURCE=""
FASTX_TOOLKIT=""
ANACONDA_PYTHON="/root/Descargas/env/bin/python"
BOWTIE2="/root/.conda/envs/bowtie2/bin/bowtie2"
ATS=""
R="/opt/R/4.0.0/bin/R"
PYTHONWNUMPY=""
GCC="/usr/bin/gcc"

CUTADAPT="/root/.conda/envs/cutadaptenv/bin/cutadapt"
MUSCLE="/home/dna_server/Documentos/anacapa/anacapa/Anacapa_db/muscle"
RUNNER="/bin/bash"
QUEUESUBMIT="qsub"
export PATH="/usr/local/anacapa/miniconda/bin:$PATH"
```
I am currently missing the fastx_toolkit path, since there is no fastx-toolkit executable. Is there any specific executable I should use? I installed fastx using bioconda (conda install fastx_toolkit). 

Besides this problem, when I run the code I get the following error:

`cutadapt: error: unrecognized arguments: -f /home/dna_server/Documentos/eDNA_analysis/HN00160001/anacapa_QC_dada2_output//QC/fastq/At-F-10_1.fastq /home/dna_server/Documentos/eDNA_analysis/HN00160001/anacapa_QC_dada2_output//QC/fastq/At-F-10_2.fastq`

I guess the cutadapt loads but it cannot process the -f parameter, but I don't know how to solve this. I am not a programmer, so I am sure am missing something here. I would appreciate any help!

thanks

**Comment by gmteunisse** [comment]
Hi Juan,

I'm not a developer on Anacapa, but I'll try to help you. I think it says in the comment in the config file that you can provide the path to fastx_toolkit, which for you probably is `/root/.conda/envs/fastx_toolkit` or `/root/.conda/envs/fastx_toolkit/bin`. I'm not sure what to do about the cutadapt error; could there perhaps be a difference in versions that you're using?

If you are able to run Singularity on your server, you could install and run Anacapa using the code I provided in issue #59. This resolves all dependency issues.

Hope this helps.

**Comment by max-mapper** [comment]
It looks like cutadapt >= 3.0 changed their command line arguments https://cutadapt.readthedocs.io/en/stable/changes.html. I would try installing cutadapt 2.10 or lower

**Comment by juanboja** [comment]
> Hi Juan,
> 
> I'm not a developer on Anacapa, but I'll try to help you. I think it says in the comment in the config file that you can provide the path to fastx_toolkit, which for you probably is `/root/.conda/envs/fastx_toolkit` or `/root/.conda/envs/fastx_toolkit/bin`. I'm not sure what to do about the cutadapt error; could there perhaps be a difference in versions that you're using?
> 
> If you are able to run Singularity on your server, you could install and run Anacapa using the code I provided in issue #59. This resolves all dependency issues.
> 
> Hope this helps.

Hi gmteunisse,

Thanks for the help. I have already provided the path to the fastx_toolkit bin folder, but the problem persists, I think I need to find which program from the toolkit is being used by ANACAPA. I'll keep trying. 

JB

**Comment by juanboja** [comment]
> It looks like cutadapt >= 3.0 changed their command line arguments https://cutadapt.readthedocs.io/en/stable/changes.html. I would try installing cutadapt 2.10 or lower

Indeed maxogden, I just tried using cutadapt version 1.16 and it worked well. I am currently stuck in other steps, but I'll open another thread for that. Thanks.
