### ISSUE TITLE
Dereplicate, then learn errors; or other way around?

### ISSUE THREAD

**Issue by gauravsk** [limey-bean/Anacapa#9]
In the current version of the dada2 scripts, `learnErrors()` comes before `derepFastq()`- curious if this was a conscious choice to do something different from the [recommended workflow](https://github.com/benjjneb/dada2/blob/7d2a83125ccce2885b7a69f57384c5c7ab2ca04b/vignettes/dada2-intro.Rmd#overview-of-the-dada2-pipeline-)?

**Comment by limey-bean** [comment]
that is nuts...  I used this tutorial almost verbatim: https://benjjneb.github.io/dada2/tutorial.html

**Comment by gauravsk** [comment]
oh ha! I don't know that it matters too much either way- but I guess if there's a lot of replicates to filter out during the derep step then we can avoid biasing the input to `learnErrors()` by running derep first?
